### ISSUE TITLE
Bug - if delete Location or Homepage Property?

### ISSUE THREAD

**Issue by 1letter** [plone/Products.PlonePAS#19]
Hi,
Plone 5.0.5 Plain Installation:
1. If modify the User Property Schema via BrowserView "@@member-fields".
2. I remove the Fields "home_page" and "location", because i didn't need this fields. It can be done, because the fields are not marked as required.
3. If i add an User via self-registration, an E-Mail-Link to the Password-Reset Page is incomming.
4. I reset the Password
5. I would like login to Page with E-Mail/NewPassord i get the following Traceback:

``` text
Traceback (most recent call last):
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/OFS/SimpleItem.py", line 242, in raise_standardErrorMessage
    v = s(**kwargs)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPythonScript.py", line 127, in __call__
    return Script.__call__(self, *args, **kw)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 39, in standard_error_message
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 322, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 237, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/FSPageTemplate.py", line 177, in pt_render
    self, source, extra_context
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 87, in pt_render
    showtal=showtal)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "f9ad878abf24a9615a6a58775ff4a927.py", line 1492, in render
  File "2213748af2a59db6692d536e2622324c.py", line 1029, in render_master
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/expressions.py", line 74, in render_content_provider
    return cp.render()
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/plone.app.layout-2.5.20-py2.7.egg/plone/app/layout/viewlets/toolbar.py", line 18, in render
    return self.custom_template()
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Chameleon-2.24-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "2596ef361a21089d81922910fc015d1b.py", line 115, in render
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/plone.app.layout-2.5.20-py2.7.egg/plone/app/layout/viewlets/toolbar.py", line 27, in get_personal_bar
    viewlet.update()
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/plone.app.layout-2.5.20-py2.7.egg/plone/app/layout/viewlets/common.py", line 278, in update
    member_info = membership.getMemberInfo(userid)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Products.PlonePAS-5.0.11-py2.7.egg/Products/PlonePAS/tools/membership.py", line 392, in getMemberInfo
    'location': member.getProperty('location'),
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Products.PlonePAS-5.0.11-py2.7.egg/Products/PlonePAS/tools/memberdata.py", line 328, in getProperty
    return BaseMemberData.getProperty(self, id, default)
  File "/home/jb/Development/Plone/Plone-5.0.4/buildout-cache/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/MemberDataTool.py", line 339, in getProperty
    raise ValueError, 'The property %s does not exist' % id
ValueError: The property location does not exist

 - Expression: "provider:plone.toolbar"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 51: col 32)
 - Source:     python:plone_view.patterns_settings()"
                       ^
 - Expression: "python: view.get_personal_bar()"
 - Filename:   ... ut-2.5.20-py2.7.egg/plone/app/layout/viewlets/toolbar.pt
 - Location:   (line 3: col 33)
 - Source:     personal_bar python: view.get_personal_bar()"
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f78fe098390>
               views: <ViewMapper - at 0x7f78fc2fa3d0>
               modules: <instance - at 0x7f79059dd710>
               args: <tuple - at 0x7f790d9c4050>
               here: <ImplicitAcquisitionWrapper front-page at 0x7f78fee3cc80>
               user: <ImplicitAcquisitionWrapper - at 0x7f78fee3cf50>
               nothing: <NoneType - at 0x91a870>
               container: <ImplicitAcquisitionWrapper front-page at 0x7f78fee3cc80>
               request: <instance - at 0x7f78fedd6638>
               wrapped_repeat: <SafeMapping - at 0x7f78ff19d788>
               traverse_subpath: <list - at 0x7f78fc6addd0>
               default: <object - at 0x7f790d8e5520>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0x7f78fee3cc80>
               view: <<ViewletManager providing IToolbar> plone.toolbar at 0x7f78fc110650>
               portal_state: <PortalState plone_portal_state at 0x7f78fc2fa910>
               translate: <function translate at 0x7f78fc365488>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f78ff1e3280>
               options: {...} (0)
               target_language: de

```

I think it's a Problem in [membership.py#L378](https://github.com/plone/Products.PlonePAS/blob/master/src/Products/PlonePAS/tools/membership.py#L378)

``` python
@security.public
    def getMemberInfo(self, memberId=None):
        # Return 'harmless' Memberinfo of any member, such as Full name,
        # Location, etc
        if not memberId:
            member = self.getAuthenticatedMember()
        else:
            member = self.getMemberById(memberId)

        if member is None:
            return None

        memberinfo = {
            'fullname': member.getProperty('fullname'),
            'description': member.getProperty('description'),
            'location': member.getProperty('location'),
            'language': member.getProperty('language'),
            'home_page': member.getProperty('home_page'),
            'username': member.getUserName(),
            'has_email': bool(member.getProperty('email')),
        }

        return memberinfo
```

**Comment by gforcada** [comment]
you could do a ``member.getProperty('location') or ''`` ? Would you mind sending a pull request?

**Comment by 1letter** [comment]
I'm not a Plone Core Developer, could i send a pull request?

**Comment by gforcada** [comment]
@1letter as long as you sign the [contributors agreement](http://docs.plone.org/develop/coredev/docs/agreement.html) there's nothing that prevents you from sending pull requests.

They can be better, they can be worse, but without sending them we can not make them, together, *even better* ;-)

**Comment by ericof** [comment]
Fixed by https://github.com/plone/Products.PlonePAS/pull/20
