### ISSUE TITLE
ImportError: cannot import name IDisableCSRFProtection

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.PlonePAS#21]
```bash
Traceback (most recent call last):
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/parts/inst02/bin/interpreter", line 350, in <module>
    execfile(__file__)
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 67, in startup
    OFS.Application.import_products()
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/OFS/Application.py", line 583, in import_products
    import_product(product_dir, product_name, raise_exc=debug_mode)
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Zope2-2.13.22-py2.7.egg/OFS/Application.py", line 606, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Products.Doormat-0.7-py2.7.egg/Products/Doormat/__init__.py", line 53, in <module>
    from Products.CMFPlone.utils import ToolInit
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Products.CMFPlone-4.3.3-py2.7.egg/Products/CMFPlone/utils.py", line 31, in <module>
    from Products.PlonePAS.interfaces.plugins import IUserManagement
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Products.PlonePAS-5.0.9-py2.7.egg/Products/PlonePAS/__init__.py", line 18, in <module>
    from Products.PlonePAS.tools.membership import MembershipTool
  File "/opt/programas/zope/2.13.22/i_99424_pis/zeoclient/eggs/Products.PlonePAS-5.0.9-py2.7.egg/Products/PlonePAS/tools/membership.py", line 33, in <module>
    from plone.protect.interfaces import IDisableCSRFProtection
ImportError: cannot import name IDisableCSRFProtection
```

It should depend on [plone.protect >= 2.0.3](https://github.com/plone/plone.protect/commit/c792890c162a58b59e60aeab088d03c7475a3695)

**Comment by mauritsvanrees** [comment]
True.

But why are you using PlonePAS 5 on Plone 4.3? That should only be done when you are using plone4.csrffixes, and that package itself requires plone.protect 3.x.
Then again, recent Plone 4.3.x versions also use PlonePAS 5, but those are Plone versions that already have plone.protect 2.0.3 or higher.

But yes, easy enough to fix. I'll do that.

**Comment by idgserpro** [comment]
Because of that: https://github.com/collective/collective.fingerpointing/commit/34c151e88bf9fb44f6d900a12b01ec52e6f80cfd

And I'm using Plone 4.3.3.
